## Web Scraping of MAC

### Importing modules`

In [6]:
import requests
import re
from bs4 import BeautifulSoup
from lxml import etree
import pandas as pd
import numpy as np
import matplotlib as mp
import pprint

### Passing URL to BS4

In [4]:
URL = "https://www.maccosmetics.com/collections"
r = requests.get(URL)

soup = BeautifulSoup(r.content, 'html5lib') # If this line causes an error, run 'pip install html5lib' or install html5lib
# print(soup.prettify())

### Extracting image URL and product name

In [5]:
dict_list = soup.find_all('div', attrs = {'class': "h-full pt-5 pb-8 bg-product-card-bg"}) 
value = []
for i in dict_list:
  # print(i)
  dic = {}
  dic['image_url']=i.source['srcset']
  dic['product_name'] = i.h2.text.strip()
  value.append(dic)

pprint.pprint(value)


[{'image_url': 'https://sdcdn.io/mac/us/mac_sku_STRJ02_1x1_0.png?width=1080&height=1080',
  'product_name': 'Squirt Plumping Gloss Stick'},
 {'image_url': 'https://sdcdn.io/mac/us/mac_sku_ST2T01_1x1_0.png?width=1080&height=1080',
  'product_name': 'Connect In Colour Eye Shadow Palette: Hi-Fi Colour'},
 {'image_url': 'https://sdcdn.io/mac/us/mac_sku_ST2F01_1x1_0.png?width=1080&height=1080',
  'product_name': 'Connect In Colour Eye Shadow Palette: Rose Lens'},
 {'image_url': 'https://sdcdn.io/mac/us/mac_sku_ST2K01_1x1_0.png?width=1080&height=1080',
  'product_name': 'Connect In Colour Eye Shadow Palette: Bronze Influence'},
 {'image_url': 'https://sdcdn.io/mac/us/mac_sku_ST2L01_1x1_0.png?width=1080&height=1080',
  'product_name': 'Connect In Colour Eye Shadow Palette: Encrypted Kryptonite'},
 {'image_url': 'https://sdcdn.io/mac/us/mac_sku_NYA851_1x1_0.png?width=1080&height=1080',
  'product_name': 'Studio Fix Every-Wear All-Over Face Pen'},
 {'image_url': 'https://sdcdn.io/mac/us/mac_sku

In [6]:
image_url_list = []
product_name_list = []

for i in value:
  image_url_list.append(i['image_url'])
  product_name_list.append(i['product_name'])

print(image_url_list)
print(product_name_list)

['https://sdcdn.io/mac/us/mac_sku_STRJ02_1x1_0.png?width=1080&height=1080', 'https://sdcdn.io/mac/us/mac_sku_ST2T01_1x1_0.png?width=1080&height=1080', 'https://sdcdn.io/mac/us/mac_sku_ST2F01_1x1_0.png?width=1080&height=1080', 'https://sdcdn.io/mac/us/mac_sku_ST2K01_1x1_0.png?width=1080&height=1080', 'https://sdcdn.io/mac/us/mac_sku_ST2L01_1x1_0.png?width=1080&height=1080', 'https://sdcdn.io/mac/us/mac_sku_NYA851_1x1_0.png?width=1080&height=1080', 'https://sdcdn.io/mac/us/mac_sku_NX6403_1x1_0.png?width=1080&height=1080', 'https://sdcdn.io/mac/us/mac_sku_STG401_1x1_0.png?width=1080&height=1080', 'https://sdcdn.io/mac/us/mac_sku_S3KX01_1x1_0.png?width=1080&height=1080', 'https://sdcdn.io/mac/us/mac_sku_NY0Y03_1x1_0.png?width=1080&height=1080', 'https://sdcdn.io/mac/us/mac_sku_NY1504_1x1_0.png?width=1080&height=1080', 'https://sdcdn.io/mac/us/mac_sku_NYF101_1x1_0.png?width=1080&height=1080', 'https://sdcdn.io/mac/us/mac_sku_SWAH01_1x1_0.png?width=1080&height=1080', 'https://sdcdn.io/mac/us

### Fetching original product prize

In [7]:
original_product_prize = soup.findAll('span',attrs={'class':'font-bold'})
original_prize_list=[]
for i in original_product_prize:
    prize = i.text.strip()
    original_prize_list.append(prize)
print(original_prize_list)

['$24.00', '$54.00', '$30.00', '$30.00', '$30.00', '$35.00', '$36.00', '$36.00', '$40.00', '$35.00', '$35.00', '$45.00', '$26.00', '$40.00', '$44.00', '$34.00', '$45.00', '$33.00', '$23.00', '$28.00', '$24.00', '$23.00', '$26.00', '$26.00', '$26.00', '$29.00', '$30.00', '$16.00', '$23.00', '$45.00', '$55.00', '$49.00', '$48.00', '$37.00', '$27.00', '$23.00', '$33.00', '$18.00', '$15.00', '$34.00', '$28.00', '$54.00', '$54.00', '$30.00', '$25.00', '$31.00', '$34.00', '$31.00', '$87.00']


### Fetching discounted prize for few products

In [8]:
discounted_product_prize = soup.findAll('span',attrs={'class':'ml-2'})
discounted_prize_list=[]
for i in discounted_product_prize:
    prize = i.text.strip()
    discounted_prize_list.append(prize)
print(discounted_prize_list)

['$26.40', '$20.40', '$27.00', '$13.80', '$13.80', '$15.60', '$15.60', '$15.60', '$17.40', '$18.00', '$13.80', '$27.00', '$15.00', '$18.60', '$20.40', '$18.60']


### Fetching product feature

In [9]:
product_feature = soup.findAll('p',attrs={'class':'font-headline text-center mx-auto max-w-[380px] px-5'})
product_feature_list=[]
for i in product_feature:
  feature = i.text.strip()
  product_feature_list.append(feature)
print(product_feature_list)

['Glossy Tinted Balm, Plumps/ Nourishes Lips, Non-Sticky High Shine', 'Technicolour Eye Palette, Pigment Packed Colour in One-Swipe, Silky-Smooth Texture', 'Rosy-Toned Eye Palette, Pigment Packed Colour in One-Swipe, Silky-Smooth Texture', 'Gilded-Toned Eye Palette, Pigment Packed Colour in One-Swipe, Silky-Smooth Texture', 'Smoky-Toned Eye Palette, Pigment Packed Colour in One-Swipe, Silky-Smooth Texture', 'Multi-Use Concealer, Medium-to-Full Buildable Coverage, Natural Matte Finish', 'Lightweight Setting Powder, Dimensional Matte Finish, Sheer Coverage', 'Transparent Setting Powder, Dimensional Matte Finish, Absorbs Oil/ Controls Shine', 'For Concealers/Foundations, Angled Shape, Blends Face Products', 'Matte Bronzing Powder, Adds Warmth/Depth, Buildable/ Blendable', 'Radiant Bronzing Powder, Adds Warmth/Glow, Buildable/ Blendable', 'For Bronzing Powders, Fan-Shaped, Shades Cheeks/Face/Body', '', 'Best-Selling Classic Shades, Matte Texture, Special-Edition Packaging', 'New/Best-Selli

### Extracting URLs for individual products

In [10]:
product_url = soup.findAll('div',attrs={'class':'h-full pt-5 pb-8 bg-product-card-bg'})
url_list = []
# print(product_url)
for i in product_url:
    a_tag = i.find('a')
    url = a_tag['href']
    # print(url)
    url_list.append(url)
print(url_list)


['/product/14766/116785/products/makeup/lips/lip-balm-primer/squirt-plumping-gloss-stick', '/product/13835/115810/products/makeup/eyes/eye-palettes-kits/connect-in-colour-eye-shadow-palette-hi-fi-colour', '/product/13835/115811/products/makeup/eyes/eye-palettes-kits/connect-in-colour-eye-shadow-palette-rose-lens', '/product/13835/115813/products/makeup/eyes/eye-palettes-kits/connect-in-colour-eye-shadow-palette-bronze-influence', '/product/13835/115814/products/makeup/eyes/eye-palettes-kits/connect-in-colour-eye-shadow-palette-encrypted-kryptonite', '/product/13844/116154/products/makeup/face/concealer/studio-fix-every-wear-all-over-face-pen', '/product/13849/106954/products/makeup/face/powder/studio-fix-pro-set-blur-weightless-loose-powder', '/product/13849/112833/products/makeup/face/powder/studio-fix-pro-set-blur-weightless-loose-powder', '/product/18579/116156/products/collections/all-products/171s-smooth-edge-all-over-face-brush', '/product/13842/116033/products/makeup/face/blush-

### Extracting product benefits and ingredients

In [25]:
from bs4 import BeautifulSoup
import requests

base_url = "https://www.maccosmetics.com"
benefit_list = []
ingredient_list = []

for url in url_list:
    full_url = base_url + url
    response = requests.get(full_url)
    soup = BeautifulSoup(response.content, 'html5lib')
    
    benefit_value = soup.find('div', attrs={'id': 'product-overview--about'})
    ingredient_value = soup.find('div', attrs={'id': 'product-overview--ingredients'})
    
    
    
    if benefit_value:
        benefit_text = benefit_value.get_text().strip()
        benefit_list.append(benefit_text)
    else:
        benefit_list.append("NA")
        
    if ingredient_value:
        ingredient_text = ingredient_value.get_text().strip()
        ingredient_list.append(ingredient_text)
    else:
        ingredient_list.append("NA")
        
print(benefit_list)
print(ingredient_list)

['Imparts a glassy shineNourishes, conditions and enhances appearance of lipsInstant plumping and visible volume with subtle tingling sensationLeaves lips soft, smooth and healthy lookingWARNING:You may experience a tingle. If uncomfortable, discontinue use. Keep away from children.', 'Pigment Packed Colour in One-SwipeLightweight, silky-smooth textureEven and seamless blendabilityFormulated with up to 25% higher pigment load vs previous M·A·C Eye Shadow palettesSafe for contact lens wearersOphthalmologist-testedCan be used wet or dryWet to intensify for all-day wear, 8 hoursWet to intensify for crease-resistant, smudge-proof colour', 'Pigment Packed Colour in One-SwipeLightweight, silky-smooth textureEven and seamless blendabilityFormulated with up to 25% higher pigment load vs previous M·A·C Eye Shadow palettesSafe for contact lens wearersOphthalmologist-testedCan be used wet or dryWet to intensify for all-day wear, 8 hoursWet to intensify for crease-resistant, smudge-proof colour', 

### Extracting product usage

In [23]:
from bs4 import BeautifulSoup
import requests

base_url = "https://www.maccosmetics.com"

usage_list = []

for url in url_list:
    full_url = base_url + url
    response = requests.get(full_url)
    soup = BeautifulSoup(response.content, 'html5lib')
    
    usage_value = soup.find('div', attrs={'id': 'product-overview--product_usage'})
    
    if usage_value:
        usage_text = usage_value.get_text().strip()
        usage_list.append(usage_text)
    else:
        usage_list.append("Not found")
print(usage_list)

['Apply to clean lips as desired or over Lipstick for a glossy effect.Pair with a Lip Pencil for instantly fuller-looking lips.Pro tip: Twist the non-retractable stick until you hear one to two clicks for the optimal amount of glossy, high-shine colour. Pro-crafted to melt across lips on contact. Once you wind Squirt up – you can’t wind her back down!', 'Apply shadow using fingers, brush or sponge-tip applicator.Use a 239S Brush to press colour onto lids.Use a 217S Brush to blend colour from the creases to brow arches.Use a 219S Brush to accentuate inner corners of eyes.Use a 263S Brush to line eyes or fill in brows.', 'Apply shadow using fingers, brush or sponge-tip applicator.Use a 239S Brush to press colour onto lids.Use a 217S Brush to blend colour from the creases to brow arches.Use a 219S Brush to accentuate inner corners of eyes.Use a 263S Brush to line eyes or fill in brows.', 'Apply shadow using fingers, brush or sponge-tip applicator.Use a 239S Brush to press colour onto lids

In [30]:
print(len(product_name_list))
print(len(image_url_list))
print(len(original_prize_list))
print(len(product_feature_list))
print(len(benefit_list))
print(len(ingredient_list))
print(len(usage_list))

49
49
49
49
49
49
49


### Extracting total number of reviews

In [28]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
import time

s=Service(r"C:\Users\disha\Downloads\chromedriver_win32\chromedriver.exe")
driver = webdriver.Chrome(service=s)

base_url = "https://www.maccosmetics.com"
total_no_of_reviews_list=[]

product_name_review = []
rating_review = []
title_review = []
body_review = []

### DEMO REVIEW EXTRACTION FOR 1 PRODUCT
# temp_url = "https://www.maccosmetics.com/product/14766/116785/products/makeup/lips/lip-balm-primer/squirt-plumping-gloss-stick"

def get_soup(url):
    driver.get(url)
    time.sleep(5)
    html = driver.page_source
    soup = BeautifulSoup(html,'html.parser')
    return soup

def get_no_of_reviews(soup):
    total_reviews = soup.find('span', class_='pr-snippet-review-count')
    if total_reviews is not None:
        review_texts = int(total_reviews.get_text().split(" ")[0])
        total_no_of_reviews_list.append(review_texts)
    else:
        total_no_of_reviews_list.append(0)

def get_reviews(soup):
    product_name = soup.find('h1', attrs={'class': 'product-full__name'}).text
    product_name_review.append(product_name)
    
    product_reviews = soup.find_all('div', attrs={'class': 'pr-review'})
    
    for item in product_reviews:
            rating = float(item.find('div', attrs={'class': 'pr-snippet-stars'})['aria-label'].split(" ")[1])
            if rating:
                rating_review.append(rating)
            else:
                rating_review.append("NA")
            
            title = item.find('span', attrs={'class': 'pr-rd-review-headline pr-h2'}).text
            if title:
                title_review.append(title)
            else:
                title_review.append("NA")
            
            body = item.find('p', attrs={'class': 'pr-rd-description-text'}).text
            if body:
                body_review.append(body)
            else:
                body_review.append("NA")
    
    
for url in url_list:
    full_url = base_url + url
    soup = get_soup(full_url)
    get_no_of_reviews(soup)
    get_reviews(soup)

print(total_no_of_reviews_list)
print(product_name_review)
print(rating_review)
print(title_review)
print(body_review)

# for i in range(len(total_no_of_reviews_list)):
#     if total_no_of_reviews_list[i]>30:
#         for x in range(1,4):
#             full_url = base_url + url_list[i]
#             soup = get_soup(full_url + f'?pr_rd_page={x}')
#             get_reviews(soup)
#     else:
#         full_url = base_url + url_list[i]
#         soup = get_soup(full_url)
#         get_reviews(soup)


[244, 63, 211, 62, 65, 537, 273, 0, 3, 7, 3, 0, 0, 0, 0, 2, 1, 689, 4, 272, 453, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1590, 529, 530, 1, 358, 555, 529, 4, 95, 299, 18121, 105, 86, 70, 7, 1, 1, 0, 487]
['Squirt Plumping Gloss Stick ', 'Connect In Colour Eye Shadow Palette: Hi-Fi Colour', 'Connect In Colour Eye Shadow Palette: Rose Lens', 'Connect In Colour Eye Shadow Palette: Bronze Influence', 'Connect In Colour Eye Shadow Palette: Encrypted Kryptonite', 'Studio Fix Every-Wear All-Over Face Pen', 'Studio Fix Pro Set + Blur Weightless Loose Powder', 'Studio Fix Pro Set + Blur Weightless Loose Powder', '171S SMOOTH-EDGE ALL OVER FACE BRUSH', 'SKINFINISH SUNSTRUCK MATTE BRONZER', 'SKINFINISH SUNSTRUCK RADIANT BRONZER', '143S Bronzer Fan Brush', 'Lash Bash Mini Trio', 'Matte Lipstick / Richard Quinn', 'Extra Dimension Skinfinish / Richard Quinn', 'Prep + Prime Fix + / Richard Quinn', 'Quinning Eye Shadow Palette', 'M·A·C Locked Kiss Ink 24HR Lipcolour', 'Matte Lipstick / Mother’s Day', 'M·A·CStack W

### Storing it to a CSV file

In [34]:
csv_file = pd.DataFrame(list(zip(product_name_list, image_url_list, original_prize_list,  product_feature_list, benefit_list, ingredient_list, usage_list, total_no_of_reviews_list)), columns = ['Product Name', 'Image URL', 'Original Prize','Product Feature','Benefits','Ingredients','Usage','Number of Reviews'])
csv_file
csv_file.to_csv('Mac.csv')

In [2]:
csv_file = pd.DataFrame(list(zip(rating_review, title_review, body_review)), columns = ['Ratings', 'Title','Body'])
csv_file
csv_file.to_csv('Mac_reviews.csv')

NameError: name 'rating_review' is not defined

### Importing the dataset

In [3]:
df = pd.read_csv(r"C:\Users\disha\Downloads\Mac.csv", index_col=[0], encoding='latin1')
df.head()

Product Name    Category  \
0                        Squirt Plumping Gloss Stick   Lip Gloss   
1  Connect In Colour Eye Shadow Palette: Hi-Fi Co...  Eye Shadow   
2    Connect In Colour Eye Shadow Palette: Rose Lens  Eye Shadow   
3  Connect In Colour Eye Shadow Palette: Bronze I...  Eye Shadow   
4  Connect In Colour Eye Shadow Palette: Encrypte...  Eye Shadow   

                                           Image URL Original Prize  \
0  https://sdcdn.io/mac/us/mac_sku_STRJ02_1x1_0.p...         $24.00   
1  https://sdcdn.io/mac/us/mac_sku_ST2T01_1x1_0.p...         $54.00   
2  https://sdcdn.io/mac/us/mac_sku_ST2F01_1x1_0.p...         $30.00   
3  https://sdcdn.io/mac/us/mac_sku_ST2K01_1x1_0.p...         $30.00   
4  https://sdcdn.io/mac/us/mac_sku_ST2L01_1x1_0.p...         $30.00   

  Discounted Prize                                    Product Feature  \
0              NaN  Glossy Tinted Balm, Plumps/ Nourishes Lips, No...   
1              NaN  Technicolour Eye Palette, Pigment Packed Colou...   
2              NaN  Rosy-Toned Eye Palette, Pigment Packed Colour ...   
3              NaN  Gilded-Toned Eye Palette, Pigment Packed Colou...   
4              NaN  Smoky-Toned Eye Palette, Pigment Packed Colour...   

                                            Benefits  \
0  Imparts a glassy shineNourishes, conditions an...   
1  Pigment Packed Colour in One-SwipeLightweight,...   
2  Pigment Packed Colour in One-SwipeLightweight,...   
3  Pigment Packed Colour in One-SwipeLightweight,...   
4  Pigment Packed Colour in One-SwipeLightweight,...   

                                         Ingredients  \
0  Diisostearyl Malate, Polybutene, Polyglyceryl-...   
1  Lauroyl Lysine, Hdi/Trimethylol Hexyllactone C...   
2  Lauroyl Lysine, Hdi/Trimethylol Hexyllactone C...   
3  Lauroyl Lysine, Hdi/Trimethylol Hexyllactone C...   
4  Lauroyl Lysine, Hdi/Trimethylol Hexyllactone C...   

                                               Usage  Number of Reviews  
0  Apply to clean lips as desired or over Lipstic...                244  
1  Apply shadow using fingers, brush or sponge-ti...                 63  
2  Apply shadow using fingers, brush or sponge-ti...                211  
3  Apply shadow using fingers, brush or sponge-ti...                 62  
4  Apply shadow using fingers, brush or sponge-ti...                 65

### Preprocessing and Removing unnecessary words

In [7]:
def clean_ingredients(ingredient):
    cleaned_ingredient = re.sub(r'\([\w\s]+\)', '', ingredient)  # Remove codes
    cleaned_ingredient = cleaned_ingredient.strip()  # Remove leading/trailing space
    cleaned_ingredient = re.sub(r',\s*\d+', '', cleaned_ingredient)  # Remove numeric values
    cleaned_ingredient = cleaned_ingredient.replace('/', '')  # Replace forward slashes with spaces
    cleaned_ingredient = cleaned_ingredient.replace(']','')
    cleaned_ingredient = cleaned_ingredient.replace('[+ -','')  # Remove '[+/-'
    cleaned_ingredient = re.sub(r'PLEASE BE AWARE THAT.*$', '', cleaned_ingredient)  # Remove disclaimer
    return cleaned_ingredient

# Apply the function to the ingredients column
df['Cleaned Ingredients'] = df['Ingredients'].apply(clean_ingredients)

In [8]:
df.head()

Product Name    Category  \
0                        Squirt Plumping Gloss Stick   Lip Gloss   
1  Connect In Colour Eye Shadow Palette: Hi-Fi Co...  Eye Shadow   
2    Connect In Colour Eye Shadow Palette: Rose Lens  Eye Shadow   
3  Connect In Colour Eye Shadow Palette: Bronze I...  Eye Shadow   
4  Connect In Colour Eye Shadow Palette: Encrypte...  Eye Shadow   

                                           Image URL Original Prize  \
0  https://sdcdn.io/mac/us/mac_sku_STRJ02_1x1_0.p...         $24.00   
1  https://sdcdn.io/mac/us/mac_sku_ST2T01_1x1_0.p...         $54.00   
2  https://sdcdn.io/mac/us/mac_sku_ST2F01_1x1_0.p...         $30.00   
3  https://sdcdn.io/mac/us/mac_sku_ST2K01_1x1_0.p...         $30.00   
4  https://sdcdn.io/mac/us/mac_sku_ST2L01_1x1_0.p...         $30.00   

  Discounted Prize                                    Product Feature  \
0              NaN  Glossy Tinted Balm, Plumps/ Nourishes Lips, No...   
1              NaN  Technicolour Eye Palette, Pigment Packed Colou...   
2              NaN  Rosy-Toned Eye Palette, Pigment Packed Colour ...   
3              NaN  Gilded-Toned Eye Palette, Pigment Packed Colou...   
4              NaN  Smoky-Toned Eye Palette, Pigment Packed Colour...   

                                            Benefits  \
0  Imparts a glassy shineNourishes, conditions an...   
1  Pigment Packed Colour in One-SwipeLightweight,...   
2  Pigment Packed Colour in One-SwipeLightweight,...   
3  Pigment Packed Colour in One-SwipeLightweight,...   
4  Pigment Packed Colour in One-SwipeLightweight,...   

                                         Ingredients  \
0  Diisostearyl Malate, Polybutene, Polyglyceryl-...   
1  Lauroyl Lysine, Hdi/Trimethylol Hexyllactone C...   
2  Lauroyl Lysine, Hdi/Trimethylol Hexyllactone C...   
3  Lauroyl Lysine, Hdi/Trimethylol Hexyllactone C...   
4  Lauroyl Lysine, Hdi/Trimethylol Hexyllactone C...   

                                               Usage  Number of Reviews  \
0  Apply to clean lips as desired or over Lipstic...                244   
1  Apply shadow using fingers, brush or sponge-ti...                 63   
2  Apply shadow using fingers, brush or sponge-ti...                211   
3  Apply shadow using fingers, brush or sponge-ti...                 62   
4  Apply shadow using fingers, brush or sponge-ti...                 65   

                                 Cleaned Ingredients  
0  Diisostearyl Malate, Polybutene, Polyglyceryl-...  
1  Lauroyl Lysine, HdiTrimethylol Hexyllactone Cr...  
2  Lauroyl Lysine, HdiTrimethylol Hexyllactone Cr...  
3  Lauroyl Lysine, HdiTrimethylol Hexyllactone Cr...  
4  Lauroyl Lysine, HdiTrimethylol Hexyllactone Cr...

### Creating a bag of words (corpus of all ingredients)

In [9]:
ingredient_idx = {}
corpus = []
idx = 0 

for i in range(len(df)):    
    ingredients = df['Cleaned Ingredients'][i]
    ingredients_lower = ingredients.lower()
    tokens = ingredients_lower.split(', ')
    corpus.append(tokens)
    for ingredient in tokens:
        if ingredient not in ingredient_idx:
            ingredient_idx[ingredient] = idx
            idx += 1

In [10]:
print(ingredient_idx)

{'diisostearyl malate': 0, 'polybutene': 1, 'polyglyceryl-2 triisostearate': 2, 'bis-diglyceryl polyacyladipate-2': 3, 'capryliccapric triglyceride': 4, 'microcrystalline wax\\cera microcristallina\\cire microcristalline': 5, 'synthetic wax': 6, 'sodium hyaluronate': 7, 'butyrospermum parkii  butter': 8, 'persea gratissima  oil': 9, 'glycine soja  oil': 10, 'capsicum frutescens fruit extract': 11, 'zingiber officinale  root oil': 12, 'menthoxypropanediol': 13, 'stearalkonium hectorite': 14, 'menthol': 15, 'paraffin': 16, 'isohexadecane': 17, 'hydrogenated coconut oil': 18, 'vanillyl butyl ether': 19, 'hydrogenated polyisobutene': 20, 'methyl nicotinate': 21, 'tripeptide-1': 22, 'propylene carbonate': 23, 'ethylenepropylene copolymer': 24, 'ethylenepropylenestyrene copolymer': 25, 'butyleneethylenestyrene copolymer': 26, 'xanthan gum': 27, 'tin oxide': 28, 'synthetic fluorphlogopite': 29, 'caprylyl glycol': 30, 'hexylene glycol': 31, 'vanillin': 32, 'pentaerythrityl tetra-di-t-butyl hyd

### Creating a Document-Term matrix

In [12]:
M = len(df)
N = len(ingredient_idx)

A = np.zeros((M,N))

In [13]:
# Define the oh_encoder function
def oh_encoder(tokens):
    x = np.zeros(N)    
    for ingredient in tokens:
        # Get the index for each ingredient
        idx = ingredient_idx[ingredient]
        # Put 1 at the corresponding indices
        x[idx] = 1
    return x

In [14]:
# Make a document-term matrix
i = 0
for tokens in corpus:
    A[i, :] = oh_encoder(tokens)
    i += 1

In [15]:
print(A)

[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 1.]]
